using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections.ObjectModel;


namespace WpfApp3
{
    public class helper
    {
        public static int kakoypoisk = 0;
        public static bool WhoAreU;
        public static string Name { get; set; }
        public static string Family { get; set; }
        public static DateTime Datarojd { get; set; }
        public static string Login { get; set; }
        public static string lognuj = "";
        public static string loginUnempl = "";
        public static string Password { get; set; }
        public static string Mail { get; set; }
        public static int cod;
        public static int chanlolid;
        public static string polnayaZanyat;
        public static string chastichnayaZanyat;
        public static string proektnayaZanyat;
        public static string Volonterstvo;
        public static string Stajirovka;
        public static string polniyDen;
        public static string smenniyGrafik;
        public static string gibkiyGrafik;
        public static string udalennayaRabota;
        public static string vahtoviyMetod;
        public static string phoneNumber = "";
        public static string noviylist;
        public static string educatLvl = "";
        public static string Experience = "";
        public static string Gender = "";
        public static string City = "";
        public static string Zavedenie;
        public static string Facultet;
        public static string Specialization;
        public static string GodOkonchaniya;
        public static string Zavedenie1;
        public static string Facultet1;
        public static string Specialization1;
        public static string GodOkonchaniya1;
        public static int CountObrazov;
        public static string Valuta = "руб.";
        public static string Educationlvlll;
        public static string rodnoy = "";
        public static string pereezd = "";
        public static string pravki;
        public static string HaveACar = "Нет личного автомобиля";
        public static int Countlang = 0;
        public static string vacancyZanyat = "";
        public static string vacancyGrafik = "";
        public static string inostan1;
        public static string inostan2;
        public static string inostan3;
        public static string inostan4;
        public static string inostan5;
        public static int rezumId;
        public static int emplId;
        public static int unemploylId1;
        public static ObservableCollection<message> AllItems;
        public static string kakoytext = "80% работодателей не рассматривают кандидатов без опыта работы. Рекомендуем указать опыт или объяснить почему его нет.";
        public static string kakoytext1 = "Укажите подробно где, кем и какое количество времени вы работали. Это увеличит ваш шанс найти работу.";
        public static ObservableCollection<Country> citview = new ObservableCollection<Country>();
        public static List<City> cities = new List<City>() 
        {
            new City("Абакан"),
            new City("Альметьевск"),
            new City("Ангарск"),
            new City("Арзамас"),
            new City("Армавир"),
            new City("Артём"),
            new City("Архангельск"),
            new City("Астрахань"),
            new City("Ачинск"),
            new City("Балаково"),
            new City("Балашиха"),
            new City("Барнаул"),
            new City("Батайск"),
            new City("Белгород"),
            new City("Бердск"),
            new City("Березники"),
            new City("Бийск"),
            new City("Благовещенск"),
            new City("Братск"),
            new City("Брянск"),
            new City("Великий Новгород"),
            new City("Владивосток"),
            new City("Владикавказ"),
            new City("Владимир"),
            new City("Волгоград"),
            new City("Волжский"),
            new City("Вологда"),
            new City("Воронеж"),
            new City("Грозный"),
            new City("Дербент"),
            new City("Дзержинск"),
            new City("Димитровград"),
            new City("Долгопрудный"),
            new City("Домодедово"),
            new City("Евпатория(Крым)"),
            new City("Екатеринбург"),
            new City("Елец"),
            new City("Ессентуки"),
            new City("Железногорск"),
            new City("Жуковский"),
            new City("Зеленодольск"),
            new City("Златоуст"),
            new City("Иваново"),
            new City("Ижевск"),
            new City("Иркутск"),
            new City("Йошкар-Ола"),
            new City("Казань"),
            new City("Калининград"),
            new City("Калуга"),
            new City("Каменск-Уральский"),
            new City("Камышин"),
            new City("Каспийск"),
            new City("Кемерово"),
            new City("Керчь(Крым)"),
            new City("Киров"),
            new City("Кисловодск"),
            new City("Ковров"),
            new City("Коломна"),
            new City("Комсомольск-на-Амуре"),
            new City("Копейск"),
            new City("Королёв"),
            new City("Кострома"),
            new City("Красногорск"),
            new City("Краснодар"),
            new City("Красноярск"),
            new City("Курган"),
            new City("Курск"),
            new City("Кызыл"),
            new City("Липецк"),
            new City("Люберцы"),
            new City("Магнитогорск"),
            new City("Майкоп"),
            new City("Махачкала"),
            new City("Миасс"),
            new City("Москва"),
            new City("Мурманск"),
            new City("Муром"),
            new City("Мытищи"),
            new City("Набережные Челны"),
            new City("Назрань"),
            new City("Нальчик"),
            new City("Находка"),
            new City("Невинномысск"),
            new City("Нефтекамск"),
            new City("Нефтеюганск"),
            new City("Нижневартовск"),
            new City("Нижнекамск"),
            new City("Нижний Новгород"),
            new City("Нижний Тагил"),
            new City("Новокузнецк"),
            new City("Новомосковск"),
            new City("Новороссийск"),
            new City("Новосибирск"),
            new City("Новочебоксарск"),
            new City("Новочеркасск"),
            new City("Новошахтинск"),
            new City("Новый Уренгой"),
            new City("Ногинск"),
            new City("Норильск"),
            new City("Ноябрьск"),
            new City("Обнинск"),
            new City("Одинцово"),
            new City("Октябрьский"),
            new City("Омск"),
            new City("Орёл"),
            new City("Оренбург"),
            new City("Орехово-Зуево"),
            new City("Орск"),
            new City("Пенза"),
            new City("Первоуральск"),
            new City("Пермь"),
            new City("Петрозаводск"),
            new City("Петропавловск-Камчатский"),
            new City("Подольск"),
            new City("Прокопьевск"),
            new City("Псков"),
            new City("Пушкино"),
            new City("Пятигорск"),
            new City("Раменское"),
            new City("Реутов"),
            new City("Ростов-на-Дону"),
            new City("Рубцовск"),
            new City("Рыбинск"),
            new City("Рязань"),
            new City("Салават"),
            new City("Самара"),
            new City("Санкт-Петербург"),
            new City("Саранск"),
            new City("Саратов"),
            new City("Севастополь(Крым)"),
            new City("Северодвинск"),
            new City("Северск"),
            new City("Серпухов"),
            new City("Симферополь(Крым)"),
            new City("Смоленск"),
            new City("Сочи"),
            new City("Ставрополь"),
            new City("Старый Оскол"),
            new City("Стерлитамак"),
            new City("Сургут"),
            new City("Сызрань"),
            new City("Сыктывкар"),
            new City("Таганрог"),
            new City("Тамбов"),
            new City("Тверь"),
            new City("Тольятти"),
            new City("Томск"),
            new City("Тула"),
            new City("Тюмень"),
            new City("Улан-Удэ"),
            new City("Ульяновск"),
            new City("Уссурийск"),
            new City("Уфа"),
            new City("Хабаровск"),
            new City("Ханты-Мансийск"),
            new City("Хасавюрт"),
            new City("Химки"),
            new City("Чебоксары"),
            new City("Челябинск"),
            new City("Череповец"),
            new City("Черкесск"),
            new City("Чита"),
            new City("Шахты"),
            new City("Щёлково"),
            new City("Электросталь"),
            new City("Элиста"),
            new City("Энгельс"),
            new City("Южно-Сахалинск"),
            new City("Якутск"),
            new City("Ярославль"),




        };

        public static List<Country> countries = new List<Country>()
        {
            new Country("Абхазия"),
            new Country("Австралия"),
            new Country("Австрия"),
            new Country("Азербайджан"),
            new Country("Албания"),
            new Country("Алжир"),
            new Country("Ангола"),
            new Country("Андорра"),
            new Country("Аргентина"),
            new Country("Армения"),
            new Country("Афганистан"),
            new Country("Багамские Острова"),
            new Country("Бангладеш"),
            new Country("Барбадос"),
            new Country("Бахрейн"),
            new Country("Беларусь"),
            new Country("Белиз"),
            new Country("Бельгия"),
            new Country("Болгария"),
            new Country("Боливия"),
            new Country("Босния и Герцеговина"),
            new Country("Бразилия"),
            new Country("Бруней Даруссалам"),
            new Country("Буркина Фасо"),
            new Country("Великобритания"),
            new Country("Венгрия"),
            new Country("Венесуэла"),
            new Country("Вьетнам"),
            new Country("Габон"),
            new Country("Гвинея"),
            new Country("Германия"),
            new Country("Государство Палестина"),
            new Country("Греция"),
            new Country("Грузия"),
            new Country("Дания"),
            new Country("Демократическая Республика Конго"),
            new Country("Джибути"),
            new Country("Доминиканская Республика"),
            new Country("Египет"),
            new Country("Замбия"),
            new Country("Израиль"),
            new Country("Индия"),
            new Country("Индонезия"),
            new Country("Иордания"),
            new Country("Ирак"),
            new Country("Иран"),
            new Country("Ирландия"),
            new Country("Исландия"),
            new Country("Испания"),
            new Country("Италия"),
            new Country("Йемен"),
            new Country("Казахстан"),
            new Country("Камбоджа"),
            new Country("Канада"),
            new Country("Катар"),
            new Country("Кипр"),
            new Country("Китай"),
            new Country("Колумбия"),
            new Country("Кооперативная Республика Гайана"),
            new Country("Королевство Саудовская Аравия"),
            new Country("Кувейт"),
            new Country("Кыргызстан"),
            new Country("Лаос"),
            new Country("Латвия"),
            new Country("Ливан"),
            new Country("Ливия"),
            new Country("Литва"),
            new Country("Лихтенштейн"),
            new Country("Люксембург"),
            new Country("Македония"),
            new Country("Малайзия"),
            new Country("Мали"),
            new Country("Мальдивская Республика"),
            new Country("Мальта"),
            new Country("Марокко"),
            new Country("Мексика"),
            new Country("Молдавия"),
            new Country("Монако"),
            new Country("Монголия"),
            new Country("Мьянма"),
            new Country("Намибия"),
            new Country("Непал"),
            new Country("Нигерия"),
            new Country("Новая Зеландия"),
            new Country("Норвегия"),
            new Country("ОАЭ"),
            new Country("Объединенная Республика Танзания"),
            new Country("Оман"),
            new Country("Острова Кайман"),
            new Country("Пакистан"),
            new Country("Панама"),
            new Country("Парагвай"),
            new Country("Перу"),
            new Country("Польша"),
            new Country("Португалия"),
            new Country("Республика Бенин"),
            new Country("Республика Гаити"),
            new Country("Республика Гана"),
            new Country("Республика Гватемала"),
            new Country("Республика Зимбабве"),
            new Country("Республика Камерун"),
            new Country("Республика Кения"),
            new Country("Республика Конго"),
            new Country("Республика Коста-Рика"),
            new Country("Республика Кот-д’Ивуар"),
            new Country("Республика Куба"),
            new Country("Республика Либерия"),
            new Country("Республика Маврикий"),
            new Country("Республика Мадагаскар"),
            new Country("Республика Малави"),
            new Country("Республика Нигер"),
            new Country("Республика Никарагуа"),
            new Country("Республика Северный Судан"),
            new Country("Республика Сейшельские острова"),
            new Country("Республика Сенегал"),
            new Country("Республика Сьерра-Леоне"),
            new Country("Республика Чад"),
            new Country("Республика Эль-Сальвадор"),
            new Country("Реюньон"),
            new Country("Россия"),
            new Country("Румыния"),
            new Country("Сент-Винсент и Гренадины"),
            new Country("Сербия"),
            new Country("Сингапур"),
            new Country("Сирия"),
            new Country("Словакия"),
            new Country("Словения"),
            new Country("США"),
            new Country("Таджикистан"),
            new Country("Таиланд"),
            new Country("Тайвань"),
            new Country("Тоголезская Республика"),
            new Country("Тунис"),
            new Country("Туркменистан"),
            new Country("Турция"),
            new Country("Уганда"),
            new Country("Узбекистан"),
            new Country("Украина"),
            new Country("Уругвай"),
            new Country("Филиппины"),
            new Country("Финляндия"),
            new Country("Франция"),
            new Country("Хорватия"),
            new Country("Центральноафриканская Республика"),
            new Country("Черногория"),
            new Country("Чехия"),
            new Country("Чили"),
            new Country("Швейцария"),
            new Country("Швеция"),
            new Country("Шотландия"),
            new Country("Шри-Ланка"),
            new Country("Эквадор"),
            new Country("Эритрея"),
            new Country("Эстония"),
            new Country("Эфиопия"),
            new Country("ЮАР"),
            new Country("Южная Корея"),
            new Country("Южная Осетия"),
            new Country("Ямайка"),
            new Country("Япония")

        };
        public static List<Languagee> languages = new List<Languagee>()
        {
            new Languagee("Абазинский"),
            new Languagee("Абхазский"),
            new Languagee("Аварский"),
            new Languagee("Азербайджанский"),
            new Languagee("Албанский"),
            new Languagee("Амхарский"),
            new Languagee("Английский"),
            new Languagee("Арабский"),
            new Languagee("Армянский"),
            new Languagee("Африкаанс"),
            new Languagee("Баскский"),
            new Languagee("Башкирский"),
            new Languagee("Белорусский"),
            new Languagee("Бенгальский"),
            new Languagee("Бирманский"),
            new Languagee("Болгарский"),
            new Languagee("Боснийский"),
            new Languagee("Бурятский"),
            new Languagee("Венгерский"),
            new Languagee("Вьетнамский"),
            new Languagee("Голландский"),
            new Languagee("Греческий"),
            new Languagee("Грузинский"),
            new Languagee("Дагестанский"),
            new Languagee("Даргинский"),
            new Languagee("Датский"),
            new Languagee("Иврит"),
            new Languagee("Ингушский"),
            new Languagee("Индонезийский"),
            new Languagee("Ирландский"),
            new Languagee("Исландский"),
            new Languagee("Испанский"),
            new Languagee("Итальянский"),
            new Languagee("Кабардино-черкесский"),
            new Languagee("Казахский"),
            new Languagee("Карачаево-балкарский"),
            new Languagee("Карельский"),
            new Languagee("Каталанский"),
            new Languagee("Кашмирский"),
            new Languagee("Китайский"),
            new Languagee("Коми"),
            new Languagee("Корейский"),
            new Languagee("Креольский"),
            new Languagee("Кумыкский"),
            new Languagee("Курдский"),
            new Languagee("Кхмерский"),
            new Languagee("Кыргызский"),
            new Languagee("Лакский"),
            new Languagee("Лаосский"),
            new Languagee("Латинский"),
            new Languagee("Латышский"),
            new Languagee("Лезгинский"),
            new Languagee("Литовский"),
            new Languagee("Македонский"),
            new Languagee("Малазийский"),
            new Languagee("Мансийский"),
            new Languagee("Марийский"),
            new Languagee("Монгольский"),
            new Languagee("Немецкий"),
            new Languagee("Непальский"),
            new Languagee("Ногайский"),
            new Languagee("Норвежский"),
            new Languagee("Осетинский"),
            new Languagee("Панджаби"),
            new Languagee("Персидский"),
            new Languagee("Польский"),
            new Languagee("Португальский"),
            new Languagee("Пушту"),
            new Languagee("Румынский"),
            new Languagee("Русский"),
            new Languagee("Санскрит"),
            new Languagee("Сербский"),
            new Languagee("Словацкий"),
            new Languagee("Словенский"),
            new Languagee("Сомалийский"),
            new Languagee("Суахили"),
            new Languagee("Тагальский"),
            new Languagee("Таджикский"),
            new Languagee("Тайский"),
            new Languagee("Талышский"),
            new Languagee("Тамильский"),
            new Languagee("Татарский"),
            new Languagee("Тибетский"),
            new Languagee("Тувинский"),
            new Languagee("Турецкий"),
            new Languagee("Туркменский"),
            new Languagee("Удмуртский"),
            new Languagee("Узбекский"),
            new Languagee("Уйгурский"),
            new Languagee("Украинский"),
            new Languagee("Урду"),
            new Languagee("Финский"),
            new Languagee("Фламандский"),
            new Languagee("Французский"),
            new Languagee("Хинди"),
            new Languagee("Хорватский"),
            new Languagee("Чеченский"),
            new Languagee("Чешский"),
            new Languagee("Чувашский"),
            new Languagee("Шведский"),
            new Languagee("Эсперанто"),
            new Languagee("Эстонский"),
            new Languagee("Якутский"),
            new Languagee("Японский"),
           

        };
        
    }
}
