//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class inolanguage
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lvl { get; set; }
        public Nullable<int> rezume_id { get; set; }
    
        public virtual rezume rezume { get; set; }
    }
}
