//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public string message1 { get; set; }
        public Nullable<System.DateTime> time_of_send { get; set; }
        public string sender_name { get; set; }
        public Nullable<int> channel_id { get; set; }
    
        public virtual channel channel { get; set; }
    }
}
