//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class findjobEntities19 : DbContext
    {
        public findjobEntities19()
            : base("name=findjobEntities19")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<channel> channels { get; set; }
        public virtual DbSet<education> educations { get; set; }
        public virtual DbSet<employer> employers { get; set; }
        public virtual DbSet<favorites_for_employer> favorites_for_employer { get; set; }
        public virtual DbSet<favorites_for_unemployed> favorites_for_unemployed { get; set; }
        public virtual DbSet<inolanguage> inolanguages { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<rezume> rezumes { get; set; }
        public virtual DbSet<unemployed> unemployeds { get; set; }
        public virtual DbSet<vacancy> vacancies { get; set; }
    }
}
