//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rezume()
        {
            this.educations = new HashSet<education>();
            this.favorites_for_employer = new HashSet<favorites_for_employer>();
            this.inolanguages = new HashSet<inolanguage>();
        }
    
        public int id { get; set; }
        public string phone_number { get; set; }
        public string city { get; set; }
        public string citizenship { get; set; }
        public string experience_job { get; set; }
        public string WhyNot { get; set; }
        public string career_objective { get; set; }
        public Nullable<int> salary { get; set; }
        public string currency { get; set; }
        public string education_lvl { get; set; }
        public string native_language { get; set; }
        public string about_myself { get; set; }
        public string moving { get; set; }
        public string busyness { get; set; }
        public string schedule { get; set; }
        public string is_have_car { get; set; }
        public string category_of_rights { get; set; }
        public Nullable<System.DateTime> datetime_of_public { get; set; }
        public Nullable<int> unemployed_id { get; set; }
        public string gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<education> educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorites_for_employer> favorites_for_employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inolanguage> inolanguages { get; set; }
        public virtual unemployed unemployed { get; set; }
    }
}
