//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vacancy()
        {
            this.favorites_for_unemployed = new HashSet<favorites_for_unemployed>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> salary { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string type_of_employment { get; set; }
        public string schedule { get; set; }
        public Nullable<System.DateTime> public_time { get; set; }
        public Nullable<int> employer_id { get; set; }
        public string currency { get; set; }
        public string from_or_to { get; set; }
    
        public virtual employer employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorites_for_unemployed> favorites_for_unemployed { get; set; }
    }
}
